# main function (used for retrying the game)
def main():
    
    # library
    import random

    # list of colours
    colours = ['R', 'B', 'G', 'Y']

    # the codes guessed by the player
    guess_codes = []

    # the codes generated by the computer
    comp_codes = []

    # temporary lists
    temp1 = []
    temp2 = []

    # attempts
    attempts = 0

    # randomize the order of the colours
    def randomize():
        for i in range(1,5):
            comp_codes.append(random.choice(colours))
        
        
                    
    # displaying the clues
    def clues(clue1, clue2):
        print('correct colour in correct position: ',clue1)
        print('correct colour in wrong position: ',clue2)          

    randomize()
        
    # interface
    print('')
    star130 = 130*'*'
    print(star130)
    print('\t                                          MASTERMIND')
    print(star130)
    print('')
    print(' HOW TO PLAY?')
    print(' 1.Players are given four colours to select from [RED, BLUE, GREEN, YELLOW]')
    print(' 2.To select the colours, input: [R-RED, B-BLUE, G-GREEN, Y-YELLOW]')
    print(' 3.Players can only select up to 4 colours each round.')
    print(' For example: R')
    print('              B')
    print('              G')
    print('              Y')
    print(' [RED, BLUE, GREEN, YELLOW]')
    print(' 4.Hints will be given after each round based on the selected colours.')
    print(' 5.The goal is to use as little attempts possible to guess the 4 colours in correct arrangement generated by the computer.')
    print(' GOOD LUCK!')
    print('')
    print(star130)
    print('')
    
    while True:
        attempts += 1
                
        while len(guess_codes) != 4:
            user_input = input(' make your guess: ').upper()
                            
            if user_input not in colours:
                print(' select one of the four available colours! for example: R, B, G, Y')
                print('')
                
            else:
                guess_codes.append(user_input)
                        
        print(' your guess is: ',guess_codes)
        print('')        
                
        # algorithm to determine the clues for:
        # -correct colour correct place
        b = 0
        clue1 = 0
        
        while b < len(guess_codes):
            
            if guess_codes[b] == comp_codes[b]:
                clue1 += 1
            
            else:
                temp1.append(guess_codes[b])
                temp2.append(comp_codes[b])
            b += 1
            
        # -correct colour different place       
        c = 0
        clue2 = 0
        
        while c < len(temp1):
            d = 0
            
            while d < len(temp2):
                
                if temp1[c] == temp2[d]:
                    temp2.pop(d)
                    clue2 += 1
                    break
                
                else:
                    d += 1
            c += 1   
                    
        # winning condition and breaking the loop 
        if guess_codes == comp_codes:
            clues(clue1, clue2)
            print('')
            print(' CONGRATULATIONS ON CRACKING THE CODE!, you took',attempts,'attempts')
            print('')
            break
        
        else:
            clues(clue1, clue2)
            guess_codes = []
            temp1 = []
            temp2 = []
            print(star130)

# retry loop
main()
while True:
    try:
        print(' do you want to play again?')
        retry = int(input(' input 1 to play again or 2 to exit: '))
        if retry == 1:
            main()
            
        else:
            retry == 2
            print(' THANK YOU FOR PLAYING!')
            exit()
            
            
    except:
        print(' invalid input! please type 1 or 2 only.')
    

    

